# Generated by Django 5.0.6 on 2024-06-17 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Profesor', models.CharField(max_length=200)),
                ('constelacionnesDadas', models.CharField(choices=[('Relación padres-hijos', 'relación padres-hijos'), ('Pareja', 'pareja'), ('Excluidos', 'excluidos'), ('Divorcios o separaciones', 'divorcios o separaciones'), ('Trabajo', 'trabajo'), ('Guerras', 'guerras'), ('Muertes tempranas', 'muertes tempranas'), ('otros', 'Otros')], default='Ninguna', max_length=40)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fechaPublicacion', models.DateTimeField(auto_now_add=True)),
                ('telefonoContacto', models.IntegerField()),
                ('emailContacto', models.EmailField(max_length=254)),
                ('imagendeProfesor', models.ImageField(blank=True, null=True, upload_to='imagenes/')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['usuario', '-fechaPublicacion'],
            },
        ),
    ]
