# Generated by Django 5.0.6 on 2024-06-17 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_profesores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constelaciones',
            name='imagendeconstelacion',
            field=models.ImageField(blank=True, null=True, upload_to='static/imagenes'),
        ),
    ]
