# Generated by Django 5.0.6 on 2024-06-17 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_constelaciones_imagendeconstelacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constelaciones',
            name='imagendeconstelacion',
            field=models.ImageField(blank=True, null=True, upload_to='app/static/imagenes'),
        ),
    ]
