# Generated by Django 5.0.6 on 2024-06-20 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_constelaciones_imagendeconstelacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constelaciones',
            name='imagendeconstelacion',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
    ]
