# Generated by Django 5.0.6 on 2024-06-21 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_profesores_imagendeprofesor_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioProfesores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('fechaComentario', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Comentarios', to='app.profesores')),
            ],
            options={
                'ordering': ['-fechaComentario'],
            },
        ),
    ]
